create table manufacturers (
  manufacturer_id smallint GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
  name text not null,
  full_name text not null
);

create table people (
  opdb_person_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  UNIQUE(opdb_person_id, name)
);

create table images (
  group_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text,
  is_primary boolean NOT NULL DEFAULT false,
  type text NOT NULL,
  CONSTRAINT chk_images_type CHECK (type IN ('backglass', 'cabinet', 'closeup', 'other', 'playfield'))
);

CREATE TABLE image_variants (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_id uuid NOT NULL REFERENCES images(group_id) ON DELETE CASCADE,
    variant text NOT NULL,
    url text NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    UNIQUE (group_id, variant),
    CONSTRAINT chk_image_variants_url CHECK (url ~* '^https?://'),
    CONSTRAINT chk_image_variants_variant CHECK (variant IN ('medium', 'large', 'small'))
);

create table features (
  feature_id smallint generated by DEFAULT as identity PRIMARY KEY,
  name text not null,
  group_name text not null
);

create table opdb (
  opdb_id text PRIMARY KEY,
  opdb_group text NOT NULL,
  opdb_machine text,
  name text NOT NULL,
  short_name text,
  common_name text,
  name_sort text,
  year smallint,
  manufacture_date date NOT NULL,
  description text,
  type text,
  display text,
  player_count smallint,
  physical_machine boolean NOT NULL,
  manufacturer_id smallint REFERENCES manufacturers(manufacturer_id),
  ipdb_id smallint CHECK (ipdb_id IS NULL OR ipdb_id > 0),
  pinball_primer_url text,
  pinball_rules_url text,
  pinball_cards_url text,
  bobs_guide_url text,
  competition_setup_url text,
  competition_notes_url text,
  has_competition_notes bool NOT NULL,
  has_competition_setup bool NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  entry_type text,
  keywords text[],
  CONSTRAINT chk_opdb_year CHECK (year BETWEEN 1900 AND 2100),
  CONSTRAINT chk_opdb_opdb_id CHECK (opdb_id ~ '^G[A-Za-z0-9]{4}(-M[A-Za-z0-9]{4})?(-A[A-Za-z0-9]{4})?$'),
  CONSTRAINT chk_opdb_opdb_group CHECK (opdb_group ~ '^G[A-Za-z0-9]{4}$'),
  CONSTRAINT chk_opdb_pinball_primer_url CHECK (pinball_primer_url IS NULL OR pinball_primer_url ~* '^https?://'),
  CONSTRAINT chk_opdb_pinball_rules_url CHECK (pinball_rules_url IS NULL OR pinball_rules_url ~* '^https?://'),
  CONSTRAINT chk_opdb_pinball_cards_url CHECK (pinball_cards_url IS NULL OR pinball_cards_url ~* '^https?://'),
  CONSTRAINT chk_opdb_bobs_guide_url CHECK (bobs_guide_url IS NULL OR bobs_guide_url ~* '^https?://'),
  CONSTRAINT chk_opdb_competition_setup_url CHECK (competition_setup_url IS NULL OR competition_setup_url ~* '^https?://'),
  CONSTRAINT chk_opdb_competition_notes_url CHECK (competition_notes_url IS NULL OR competition_notes_url ~* '^https?://'),
  CONSTRAINT chk_opdb_entry_type CHECK (entry_type IN ('alias', 'machine', 'machineGroup'))
);

CREATE INDEX idx_opdb_manufacturer_id ON opdb (manufacturer_id);
CREATE INDEX idx_opdb_group ON opdb (opdb_group);

CREATE TABLE opdb_people (
    opdb_id text NOT NULL REFERENCES opdb(opdb_id) ON DELETE CASCADE,
    opdb_person_id smallint NOT NULL REFERENCES people(opdb_person_id) ON DELETE CASCADE,
    role_name text NOT NULL,
    person_index smallint NOT NULL,
    PRIMARY KEY (opdb_id, opdb_person_id,role_name)
);

CREATE INDEX idx_opdb_people_person_id ON opdb_people (opdb_person_id);

CREATE TABLE opdb_features (
    opdb_id text NOT NULL REFERENCES opdb(opdb_id) ON DELETE CASCADE,
    feature_id smallint NOT NULL REFERENCES features(feature_id) ON DELETE CASCADE,
    PRIMARY KEY (opdb_id, feature_id)
);

CREATE INDEX idx_opdb_features_feature_id ON opdb_features (feature_id);

CREATE TABLE opdb_images (
    opdb_id text NOT NULL REFERENCES opdb(opdb_id) ON DELETE CASCADE,
    group_id uuid NOT NULL REFERENCES images(group_id) ON DELETE CASCADE,
    PRIMARY KEY (opdb_id, group_id)
);

CREATE INDEX idx_opdb_images_group_id ON opdb_images (group_id);
